// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyDxyBHoboirDPutvPhee6VJBpzEvkAi0',
    appId: '1:812282489160:web:f85bcaf223a9aae2caab7d',
    messagingSenderId: '812282489160',
    projectId: 'finance-6ce14',
    authDomain: 'finance-6ce14.firebaseapp.com',
    storageBucket: 'finance-6ce14.appspot.com',
    measurementId: 'G-2J4Z7TPDT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnqRwLnWtK791BN2ZCAiDXMBHS3y9J99A',
    appId: '1:812282489160:android:6b30b18f580f5c7fcaab7d',
    messagingSenderId: '812282489160',
    projectId: 'finance-6ce14',
    storageBucket: 'finance-6ce14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJE6ncS99XJFQ1Wi8daUqAC7IoMF69T_Q',
    appId: '1:812282489160:ios:cf8ab0d1d49835b8caab7d',
    messagingSenderId: '812282489160',
    projectId: 'finance-6ce14',
    storageBucket: 'finance-6ce14.appspot.com',
    iosBundleId: 'com.frutterlabs.financeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJE6ncS99XJFQ1Wi8daUqAC7IoMF69T_Q',
    appId: '1:812282489160:ios:cf8ab0d1d49835b8caab7d',
    messagingSenderId: '812282489160',
    projectId: 'finance-6ce14',
    storageBucket: 'finance-6ce14.appspot.com',
    iosBundleId: 'com.frutterlabs.financeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyDxyBHoboirDPutvPhee6VJBpzEvkAi0',
    appId: '1:812282489160:web:befd246f2a7e9ab3caab7d',
    messagingSenderId: '812282489160',
    projectId: 'finance-6ce14',
    authDomain: 'finance-6ce14.firebaseapp.com',
    storageBucket: 'finance-6ce14.appspot.com',
    measurementId: 'G-N9RLS19RQ0',
  );
}
